### ISSUE TITLE
Not working, selects all files

### ISSUE THREAD

**Issue by runaroundhome** [ntv1000/rtorrent-cleanup#2]
So I just ran a dry run and it selected everything. Then I tried it with the test files included in this repo and it did the same. Am I doing something wrong?

    ./rtorrent_cleanup.py  ./tests/testenv_template/workingdir/ ./tests/testenv_template/downloaddir/ --dry --debug

<pre>debug_flag=True
dryrun_flag=True
rtorrent_working_dir=./tests/testenv_template/workingdir/
rtorrent_download_dirs=['./tests/testenv_template/downloaddir/']
found 2 downloaded files
found 2 rtorrent files
single-file torrent: {{pathtotestenv}}/downloaddir/file1.txt
multi-file torrent: {{pathtotestenv}}/downloaddir/directory1
found 2 files that were referenced
found 2 files that were not referenced
deleting all unreferenced files will free up 16B of storage
Not referenced files:
./tests/testenv_template/downloaddir/directory1
./tests/testenv_template/downloaddir/file1.txt
</pre>

It sees the 2 files, but seems to think they are both referenced and not referenced.

When I don't do a dry run it deletes `directory1` and `file1.txt`

Running the script on `Debian 8.8`, and `Python 2.7.9`

**Comment by ntv1000** [comment]
The test files don't work like that, because they are intended to be run with `nosetests` (a test framework for python). The paths in the torrent files include a `{{pathtotestenv}}` which is replaced by nosetests when the tests are run. Running it like that doesn't work, because the script just takes the paths as they are. 

On the one hand, it seems you are using the script correctly and it shouldn't "select everything" when there are files that are referenced in rtorrent. On the other hand, when the script marks all files for deletion, it really sounds like the script gets supplied with the wrong path.

I recently had a problem with weird drive setups (session directory on an internal drive, download directory on an external drive), which should be fixed, but maybe you have some setup where the script messes up the paths?

**Comment by adriel** [comment]
Hmm, well one thing that might be different is that both the session and download directories are located inside Docker containers, and are mounted onto the host machine, where I'm running this script. I can't run it inside the container as it doesn't have Python installed. Could that be it?

**Comment by runaroundhome** [comment]
Hmm, well one thing that might be different is that both the session and download directories are located inside Docker containers, and are mounted onto the host machine, where I'm running this script. I can't run it inside the container as it doesn't have Python installed. Could that be it?

**Comment by ntv1000** [comment]
Yes, I think so. The script reads the paths from the torrent files in the session directory. In your case I imagine that they contain the "internal" (non-mounted) docker paths. If you mount both directories and give the script the mounted paths, the script (working outside of the docker container) comes to the conclusion, that none of the files are referenced by rtorrent, since all torrents in rtorrent have the path "/inside/docker/container" while the download directories are "/outside/docker/container". Nothing matches up, everything is marked for deletion.

I don't really have a good idea to handle such a case. The best solution I can think of is giving an error that says that there are no matching paths and showing the different paths so that it will be obvious to the user what is going on.

A solution for you would be to [run the script inside the docker container](https://stackoverflow.com/questions/31578446/running-a-script-inside-a-docker-container-using-shell-script) and to give it the "internal" session and download directory paths. That should work.

**Comment by runaroundhome** [comment]
Aaaah, yes that must be it. I can't run the script inside the container as it doesn't have Python installed. But I'm going to mount the files in the same location on the host as they are in the container and see how I go.

**Edit:**
Yep, I symlink both folders to the same locations and it worked!
Thanks!
